server:
  port: 8081
  servlet:
    context-path: /web

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useSSL=false&serverTimezone=Asia/Shanghai
    password: 123456
    username: root

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.demo.**.entity
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
token:
  # 过期时间(单位：分钟)
  expireTime: 3